import json
import os
from google import genai
from groq import Groq
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables
env_path = Path(__file__).parent.parent / ".env"
load_dotenv(dotenv_path=env_path)

# Configure API keys
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")

def ai_generate_json(prompt, system_instruction=""):
    """
    Tries Gemini first, falls back to Groq if Gemini fails.
    """
    # 1. Try Gemini
    try:
        client = genai.Client(api_key=GOOGLE_API_KEY)
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            config={"response_mime_type": "application/json"}
        )
        return json.loads(response.text)
    except Exception as e:
        print(f"   [WARN] Gemini Brain failed: {e}. Trying Groq Fallback...")
        
    # 2. Try Groq
    if GROQ_API_KEY:
        try:
            client = Groq(api_key=GROQ_API_KEY)
            chat_completion = client.chat.completions.create(
                messages=[{"role": "user", "content": prompt}],
                model="llama-3.3-70b-versatile",
                response_format={"type": "json_object"}
            )
            return json.loads(chat_completion.choices[0].message.content)
        except Exception as e:
            print(f"   [ERROR] Groq Brain fallback failed: {e}")
            
    return None

def load_organization_profile():
    """
    Loads the global organization profile generated by Step 0 (Org Scanner).
    """
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    profile_path = os.path.join(base_dir, "contracts", "org_profile.json")
    
    if os.path.exists(profile_path):
        with open(profile_path, "r", encoding="utf-8") as f:
            return json.load(f)
    return None

def main():
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    incoming_papers_path = os.path.join(base_dir, "contracts", "incoming_papers.json")
    pending_actions_path = os.path.join(base_dir, "contracts", "pending_actions.json")
    live_trends_path = os.path.join(base_dir, "contracts", "live_trends.json")

    # Read Enterprise Context (Org Profile)
    org_profile = load_organization_profile()
    if not org_profile:
        print("Error: No Samsung organization profile found in /contracts. Run Step 0 first.")
        return

    # Read incoming papers
    try:
        with open(incoming_papers_path, "r", encoding="utf-8") as f:
            papers = json.load(f)
    except FileNotFoundError:
        print(f"Error: Could not find {incoming_papers_path}")
        return

    # ==============================================================
    # 1. OPPORTUNITY ANALYSIS
    # ==============================================================
    prompt_actions = f"""
You are the Lead AI Architect for Samsung's Enterprise Research Division.
Organization Profile:
{json.dumps(org_profile, indent=2)}

Research Papers:
{json.dumps(papers, indent=2)}

Find EXACTLY ONE paper for a high-value optimization.
Return as a JSON array with exactly one object:
[
  {{
    "department": "Target repo name",
    "target_entity": "module name",
    "paper_title": "Title",
    "url": "url",
    "type": "Opportunity",
    "reason": "Why it solves an org issue or goal.",
    "action": "Code suggestion"
  }}
]
"""

    print("Analyzing Samsung Enterprise Opportunities...")
    parsed_output = ai_generate_json(prompt_actions)
    if parsed_output:
        if not isinstance(parsed_output, list): parsed_output = [parsed_output]
        with open(pending_actions_path, "w", encoding="utf-8") as f:
            json.dump(parsed_output, f, indent=2)
        print(f"[OK] Generated enterprise action.")

    # ==============================================================
    # 2. TREND & THREAT ANALYSIS
    # ==============================================================
    prompt_trends = f"""
You are the Head of Market Intelligence for Samsung. 
Based on our Org Profile and these papers, identify ONE major threat/trend.
Return as a JSON array with exactly one object:
[
  {{
    "affected_departments": ["Repo A"],
    "cluster_name": "Trend Name",
    "paper_count": 5,
    "timeframe_days": 14,
    "key_competitors": ["Apple"],
    "implication": "Threat assessment.",
    "trend_score": 95,
    "top_paper": {{ "title": "Paper", "url": "url" }}
  }}
]
"""

    print("Analyzing Samsung Enterprise Macro Threats...")
    parsed_trends = ai_generate_json(prompt_trends)
    if parsed_trends:
        if not isinstance(parsed_trends, list): parsed_trends = [parsed_trends]
        with open(live_trends_path, "w", encoding="utf-8") as f:
            json.dump(parsed_trends, f, indent=2)
        print(f"[OK] Generated enterprise threat report.")

if __name__ == "__main__":
    main()
