"""
Member 4 – The Communicator | outputs/auto_pr.py
=================================================
THE AUTO-CODER  🤖⚡
---------------------
God-Tier upgrade: instead of telling engineers *what* to change, RADAR actually
writes the code itself and submits a ready-to-merge Pull Request.

Pipeline
--------
1. Read `contracts/pending_actions.json`  (produced by Member 3 Brain Engine)
2. For every Opportunity alert that carries a `target_entity` field:
   a. Feed the paper abstract + action recommendation to Google Gemini
      (or use --mock to generate a rich template locally with no API call)
   b. Gemini writes a production-quality Python implementation
   c. Commit the generated .py file to a fresh feature branch on GitHub
   d. Open a Pull Request with a rich Markdown body
3. Print a summary of every PR URL created

Usage
-----
    pip install PyGithub google-genai

    # Normal mode (requires a valid Gemini API key with quota)
    python outputs/auto_pr.py

    # Mock mode — skips Gemini, generates a template locally, still creates the PR
    python outputs/auto_pr.py --mock
"""

import json
import os
import re
import sys
import textwrap
import time
from datetime import datetime, timezone
from pathlib import Path

from google import genai
from google.genai import types as genai_types
from github import Github, GithubException
from dotenv import load_dotenv

# Ensure project root is in path (needed when run as subprocess)
sys.path.insert(0, str(Path(__file__).parent.parent))
load_dotenv(dotenv_path=Path(__file__).parent.parent / ".env")

# ---------------------------------------------------------------------------
# Configuration – set via environment variables OR edit directly here
# ---------------------------------------------------------------------------
GITHUB_TOKEN:   str = os.getenv("GITHUB_TOKEN")
GITHUB_ORG:     str = os.getenv("GITHUB_ORG")   # New: Support for Org-wide PRs
GITHUB_REPO:    str = os.getenv("GITHUB_REPO")
GOOGLE_API_KEY: str = os.getenv("GOOGLE_API_KEY")

# gemini-2.0-flash-lite: confirmed available on free-tier API keys
GEMINI_MODEL = "gemini-2.5-flash"

# Branch prefix for every auto-generated PR
BRANCH_PREFIX = "radar/auto-coder"

# GitHub label for auto-generated PRs
PR_LABEL_NAME  = "RADAR: Auto-Coder"
PR_LABEL_COLOR = "6f42c1"   # purple

# Contract file (relative to this script)
SCRIPT_DIR           = Path(__file__).parent        # outputs/
PENDING_ACTIONS_PATH = SCRIPT_DIR.parent / "contracts" / "pending_actions.json"

# Where inside the repo to commit generated code
GENERATED_CODE_DIR = "generated"  # → SAMSUNG_PRISM/generated/<entity>.py


# ---------------------------------------------------------------------------
# I/O helpers
# ---------------------------------------------------------------------------

def safe_print(msg: str) -> None:
    """UTF-8-safe print (handles emoji on Windows CMD)."""
    sys.stdout.buffer.write((msg + "\n").encode("utf-8", errors="replace"))
    sys.stdout.buffer.flush()


def load_pending_actions() -> list[dict]:
    """Load and validate contracts/pending_actions.json."""
    if not PENDING_ACTIONS_PATH.exists():
        safe_print(f"[ERROR] Contract file not found: {PENDING_ACTIONS_PATH}")
        sys.exit(1)
    with open(PENDING_ACTIONS_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    # Support both flat list (old) and {"actions": [...]} (new)
    if isinstance(data, dict) and "actions" in data:
        return data["actions"]
    if isinstance(data, list):
        return data

    safe_print("[ERROR] pending_actions.json must be a JSON array or {'actions': []} object.")
    sys.exit(1)


# ---------------------------------------------------------------------------
# Mock code generator (no API call — for demo / quota-free runs)
# ---------------------------------------------------------------------------

def generate_mock_code(alert: dict) -> str:
    """
    Build a complete, runnable Python implementation template based on the
    alert metadata alone.  Used when --mock is passed or Gemini is unavailable.
    """
    paper_title   = alert.get("paper_title",   "Unknown Paper")
    url           = alert.get("url",            "")
    reason        = alert.get("reason",         "")
    action        = alert.get("action",         "")
    target_entity = alert.get("target_entity",  "algorithm")
    generated_at  = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Derive a clean class/function name
    func_name = re.sub(r"[^a-zA-Z0-9_]", "_", target_entity).strip("_")

    return textwrap.dedent(f'''
    """
    Auto-generated by RADAR Auto-Coder
    Generated : {generated_at}

    Source Paper
    ------------
    Title : {paper_title}
    URL   : {url}

    Why This Matters
    ----------------
    {reason}

    Recommended Action
    ------------------
    {action}
    """

    import math
    from typing import Optional

    import numpy as np

    try:
        import torch
        import torch.nn as nn
        _TORCH_AVAILABLE = True
    except ImportError:
        _TORCH_AVAILABLE = False


    # ---------------------------------------------------------------------------
    # Core implementation
    # ---------------------------------------------------------------------------

    def {func_name}(
        weights: "np.ndarray | torch.Tensor",
        bits: int = 4,
        group_size: int = 128,
        symmetric: bool = True,
        clamp_outliers: bool = True,
        outlier_threshold: float = 3.0,
    ):
        """
        Implement the algorithm described in: {paper_title}

        Parameters
        ----------
        weights : np.ndarray or torch.Tensor
            The weight matrix to process.
        bits : int
            Target bit-width (default: 4).
        group_size : int
            Number of elements per quantisation group (default: 128).
        symmetric : bool
            Use symmetric quantisation around zero (default: True).
        clamp_outliers : bool
            Clamp statistical outliers before quantising (default: True).
        outlier_threshold : float
            Std-dev multiplier for outlier detection (default: 3.0).

        Returns
        -------
        Same type as input — quantised weights dequantised back to float32.
        """
        use_torch = _TORCH_AVAILABLE and hasattr(weights, "dim")

        if use_torch:
            w = weights.float().cpu()
        else:
            w = np.asarray(weights, dtype=np.float32)

        # --- Step 1: Reshape into groups -----------------------------------
        original_shape = w.shape if use_torch else w.shape
        flat = w.reshape(-1) if use_torch else w.ravel()
        n = flat.shape[0] if use_torch else flat.size
        pad = (group_size - n % group_size) % group_size

        if pad:
            zeros = (torch.zeros(pad) if use_torch else np.zeros(pad, dtype=np.float32))
            flat = (torch.cat([flat, zeros]) if use_torch else np.concatenate([flat, zeros]))

        groups = flat.reshape(-1, group_size)

        # --- Step 2: Optional outlier clamping -----------------------------
        if clamp_outliers:
            if use_torch:
                mu, sigma = groups.mean(dim=1, keepdim=True), groups.std(dim=1, keepdim=True)
            else:
                mu, sigma = groups.mean(axis=1, keepdims=True), groups.std(axis=1, keepdims=True)
            lo, hi = mu - outlier_threshold * sigma, mu + outlier_threshold * sigma
            groups = (torch.clamp(groups, lo, hi) if use_torch
                      else np.clip(groups, lo, hi))

        # --- Step 3: Compute scale (and zero-point for asymmetric) ---------
        qmin = -(2 ** (bits - 1))       # e.g. -8  for 4-bit
        qmax =  (2 ** (bits - 1)) - 1   # e.g.  7  for 4-bit

        if symmetric:
            if use_torch:
                abs_max = groups.abs().max(dim=1, keepdim=True).values
            else:
                abs_max = np.abs(groups).max(axis=1, keepdims=True)
            scale = abs_max / qmax
            scale = (torch.clamp(scale, min=1e-8) if use_torch
                     else np.maximum(scale, 1e-8))
            zero_point = 0
        else:
            if use_torch:
                g_min = groups.min(dim=1, keepdim=True).values
                g_max = groups.max(dim=1, keepdim=True).values
            else:
                g_min = groups.min(axis=1, keepdims=True)
                g_max = groups.max(axis=1, keepdims=True)
            scale = (g_max - g_min) / (qmax - qmin)
            scale = (torch.clamp(scale, min=1e-8) if use_torch
                     else np.maximum(scale, 1e-8))
            zero_point = qmin - g_min / scale

        # --- Step 4: Quantise and dequantise (simulated quantisation) ------
        q = groups / scale + (0 if symmetric else zero_point)
        q = (torch.clamp(q.round(), qmin, qmax) if use_torch
             else np.clip(np.round(q), qmin, qmax))
        dq = (q - (0 if symmetric else zero_point)) * scale

        # --- Step 5: Restore original shape --------------------------------
        result = dq.reshape(-1)[:n]
        result = result.reshape(original_shape)
        return result if use_torch else result


    # ---------------------------------------------------------------------------
    # Demo
    # ---------------------------------------------------------------------------

    if __name__ == "__main__":
        print("RADAR Auto-Coder — {func_name} demo")
        print("Source : {url}")
        print()

        # Synthetic weight matrix (simulates a transformer layer)
        rng = np.random.default_rng(42)
        W = rng.standard_normal((128, 256)).astype(np.float32)
        print(f"Original  | mean={{W.mean():.4f}}  std={{W.std():.4f}}  range=[{{W.min():.3f}}, {{W.max():.3f}}]")

        W_q = {func_name}(W, bits=4, group_size=64, symmetric=True)
        error = np.abs(W - W_q).mean()
        print(f"Quantised | mean={{W_q.mean():.4f}}  std={{W_q.std():.4f}}  MAE={{error:.6f}}")
        print(f"\nMemory reduction: {{(1 - 4/32)*100:.0f}}% (32-bit → 4-bit)")
    ''').lstrip()


# ---------------------------------------------------------------------------
# Gemini code generator
# ---------------------------------------------------------------------------

def build_gemini_prompt(alert: dict) -> str:
    """
    Construct a detailed prompt so Gemini writes a *real* Python implementation
    of the algorithm described in the ArXiv paper referenced by the alert.
    """
    paper_title   = alert.get("paper_title",   "Unknown Paper")
    url           = alert.get("url",            "")
    reason        = alert.get("reason",         "")
    action        = alert.get("action",         "")
    target_entity = alert.get("target_entity",  "improved_algorithm")
    entity_type   = alert.get("entity_type",    "function")

    prompt = textwrap.dedent(f"""
    You are an expert AI research engineer working at Samsung R&D.

    An autonomous research-monitoring agent called RADAR has flagged the following
    ArXiv paper as a high-priority opportunity for Samsung's on-device AI stack:

    PAPER TITLE : {paper_title}
    PAPER URL   : {url}
    WHY IT MATTERS:
    {reason}

    RECOMMENDED ACTION:
    {action}

    YOUR TASK
    ---------
    Write a complete, production-quality Python implementation of the core algorithm
    described in the paper above.  The implementation must:

    1. Target the entity named  `{target_entity}` (entity type: {entity_type}).
    2. Be fully self-contained — include all imports at the top.
    3. Include a detailed module-level docstring that:
       - Names the source paper and its URL
       - Summarises the mathematical idea in plain English
       - Lists any key hyperparameters and their default values
    4. Add NumPy-style docstrings to every public function / class.
    5. Include at least one concrete usage example inside an
       `if __name__ == "__main__":` block that can be run immediately.
    6. Prefer PyTorch (torch) for tensor operations; fall back to NumPy if simpler.
    7. Add inline comments explaining the mathematics / algorithm steps.
    8. Do NOT include placeholder stubs — every function must be fully implemented.

    Return ONLY the raw Python source code.  Do NOT wrap it in markdown fences.
    Do NOT add any explanation before or after the code.
    """).strip()

    return prompt


def generate_code_with_gemini(alert: dict) -> str:
    """
    Call Gemini via the google.genai SDK and return generated Python source.
    Falls back to Groq, then OpenRouter (free) if Gemini is unavailable.
    """
    import urllib.request
    prompt = build_gemini_prompt(alert)
    safe_print(f"[AI] Generating code for: {alert.get('target_entity', '?')} ...")

    # 1. Try Gemini
    if GOOGLE_API_KEY:
        try:
            client = genai.Client(api_key=GOOGLE_API_KEY)
            safe_print(f"[GEMINI] Trying {GEMINI_MODEL}...")
            response = client.models.generate_content(
                model=GEMINI_MODEL,
                contents=prompt,
                config=genai_types.GenerateContentConfig(
                    temperature=0.2,
                    max_output_tokens=8192,
                ),
            )
            return strip_markdown_fences(response.text.strip())
        except Exception as exc:
            safe_print(f"[WARN] Gemini failed: {exc}")

    # 2. Try Groq
    groq_api_key = os.getenv("GROQ_API_KEY")
    if groq_api_key:
        try:
            from groq import Groq
            client = Groq(api_key=groq_api_key)
            safe_print("[GROQ] Switching to Llama-3...")
            chat_completion = client.chat.completions.create(
                messages=[{"role": "user", "content": prompt}],
                model="llama-3.3-70b-versatile",
            )
            return strip_markdown_fences(chat_completion.choices[0].message.content.strip())
        except Exception as groq_err:
            safe_print(f"[WARN] Groq fallback failed: {groq_err}")

    # 3. Try OpenRouter (free tier — no daily limit)
    openrouter_key = os.getenv("OPENROUTER_API_KEY")
    if openrouter_key:
        free_models = [
            "google/gemma-4-31b-it:free",
            "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free",
            "nvidia/nemotron-3-super-120b-a12b:free",
        ]
        or_headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {openrouter_key}",
            "HTTP-Referer": "https://github.com/Samsung-PRISM-EdgeAI",
            "X-Title": "RADAR Auto-Coder"
        }
        for model in free_models:
            try:
                safe_print(f"[OPENROUTER] Trying {model.split('/')[1]}...")
                payload = json.dumps({
                    "model": model,
                    "messages": [{"role": "user", "content": prompt}]
                }).encode()
                req = urllib.request.Request(
                    "https://openrouter.ai/api/v1/chat/completions",
                    data=payload, headers=or_headers
                )
                r = urllib.request.urlopen(req, timeout=90)
                resp = json.loads(r.read())
                code = resp["choices"][0]["message"]["content"].strip()
                safe_print(f"[OPENROUTER] Success with {model.split('/')[1]}")
                return strip_markdown_fences(code)
            except Exception as e:
                safe_print(f"[WARN] OpenRouter {model.split('/')[1]} failed: {str(e)[:80]}")
                time.sleep(3)

    # 4. Final fallback — generate rich local template
    safe_print("[INFO] All AI providers unavailable — using rich local template.")
    return generate_mock_code(alert)


def strip_markdown_fences(code: str) -> str:
    """Strip accidental markdown fences AI models sometimes add."""
    if code.startswith("```"):
        lines = code.splitlines()
        code = "\n".join(lines[1:-1] if lines[-1].strip() == "```" else lines[1:])
    return code

    return code


# ---------------------------------------------------------------------------
# Step 2 – GitHub: branch → commit → PR
# ---------------------------------------------------------------------------

def slugify(text: str) -> str:
    """Turn arbitrary text into a safe branch-name / filename segment."""
    import re
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    return text.strip("-")[:48]


def ensure_label(repo, name: str, color: str, description: str = "") -> None:
    """Create the GitHub label if it doesn't already exist."""
    try:
        repo.get_label(name)
    except GithubException:
        try:
            repo.create_label(name=name, color=color, description=description)
            safe_print(f"[INFO] Created GitHub label: '{name}'")
        except GithubException as exc:
            safe_print(f"[WARN] Could not create label '{name}': {exc}")


def build_pr_body(alert: dict, branch: str, file_path: str, generated_at: str) -> str:
    """Compose a rich Markdown PR description."""
    paper_title   = alert.get("paper_title",   "Unknown Paper")
    url           = alert.get("url",            "")
    reason        = alert.get("reason",         "")
    action        = alert.get("action",         "")
    target_entity = alert.get("target_entity",  "N/A")
    paper_link    = f"[{paper_title}]({url})" if url else f"**{paper_title}**"

    return textwrap.dedent(f"""
    ## 🤖 RADAR Auto-Coder — Autonomous Pull Request

    > *Auto-generated by the RADAR Agent on {generated_at}*
    > Branch: `{branch}`

    ---

    ### 📄 Source Paper
    | Field | Details |
    |---|---|
    | **Title** | {paper_link} |
    | **ArXiv URL** | {url or "N/A"} |
    | **Generated File** | `{file_path}` |

    ---

    ### 🧠 Why This Matters
    > {reason}

    ---

    ### 🎯 What Was Implemented
    The RADAR Brain Engine identified `{target_entity}` as the target entity.
    Google Gemini read the paper's methodology and wrote a full Python implementation
    of the described algorithm, committed to this branch automatically.

    ---

    ### ⚡ Original Recommendation
    > {action}

    ---

    ### ✅ Review Checklist
    - [ ] Verify the generated algorithm matches the paper's formulas
    - [ ] Run the `if __name__ == "__main__":` demo locally
    - [ ] Benchmark against the baseline implementation
    - [ ] Adjust hyperparameters for Samsung target devices
    - [ ] Approve & Merge

    ---

    ### 📋 How to Test
    ```bash
    # From repo root
    pip install torch numpy
    python {file_path}
    ```

    ---
    *🔗 RADAR · Member 4: The Communicator · `outputs/auto_pr.py`*
    """).strip()


def find_best_repo(g, org_name, target_entity, fallback_repo=None):
    """Identical to dispatcher logic: find the best repo for the entity."""
    if not org_name:
        if fallback_repo:
            return g.get_repo(fallback_repo)
        return None

    try:
        org = g.get_organization(org_name)
        repos = org.get_repos()
        target_entity_clean = target_entity.lower().replace(" ", "-")
        for repo in repos:
            if target_entity_clean in repo.name.lower():
                return repo
        if fallback_repo:
            return g.get_repo(fallback_repo)
        return None
    except Exception as e:
        safe_print(f"[ERROR] Could not query organization '{org_name}': {e}")
        return None

def create_pull_request(token: str, org_name: str, fallback_repo: str, alert: dict, code: str) -> str:
    """
    1. Find target repo in Org
    2. Get default branch SHA
    3. Create feature branch
    4. Commit generated code
    5. Open PR
    """
    g    = Github(token)
    
    target_entity = alert.get("target_entity", "algorithm")
    repo = find_best_repo(g, org_name, target_entity, fallback_repo)

    if not repo:
        safe_print(f"[WARN] Skipping PR: Could not find target repo for entity '{target_entity}'")
        return None

    safe_print(f"[INFO] Routing PR for '{target_entity}' to repo: {repo.full_name}")

    slug          = slugify(target_entity)
    timestamp     = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    branch_name   = f"{BRANCH_PREFIX}/{slug}-{timestamp}"
    
    # Route code to the correct Samsung department folder
    dept = alert.get("department", "").strip()
    if dept:
        file_path = f"data/{dept}/{slug}.py"
    else:
        file_path = f"{GENERATED_CODE_DIR}/{slug}.py"

    generated_at  = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # ── 1. Get base branch SHA ───────────────────────────────────────────────
    default_branch = repo.default_branch
    base_sha       = repo.get_branch(default_branch).commit.sha
    safe_print(f"[GH]    Base branch: {default_branch} @ {base_sha[:8]}")

    # ── 2. Create feature branch ─────────────────────────────────────────────
    try:
        repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base_sha)
        safe_print(f"[GH]    Created branch: {branch_name}")
    except GithubException as exc:
        safe_print(f"[ERROR] Could not create branch '{branch_name}': {exc}")
        raise

    # ── 3. Commit the generated file ─────────────────────────────────────────
    commit_message = (
        f"feat(auto-coder): implement {target_entity} from ArXiv paper\n\n"
        f"Auto-generated by RADAR Auto-Coder on {generated_at}\n"
        f"Source: {alert.get('url', '')}"
    )

    # Check if file already exists on the branch (for update vs create)
    try:
        existing = repo.get_contents(file_path, ref=branch_name)
        repo.update_file(
            path=file_path,
            message=commit_message,
            content=code,
            sha=existing.sha,
            branch=branch_name,
        )
        safe_print(f"[GH]    Updated file: {file_path}")
    except GithubException:
        repo.create_file(
            path=file_path,
            message=commit_message,
            content=code,
            branch=branch_name,
        )
        safe_print(f"[GH]    Created file: {file_path}")

    # ── 4. Ensure label exists ───────────────────────────────────────────────
    ensure_label(
        repo, PR_LABEL_NAME, PR_LABEL_COLOR,
        "Autonomous PR created by RADAR Auto-Coder"
    )

    # ── 5. Open the Pull Request ─────────────────────────────────────────────
    pr_title = f"[RADAR Auto-Coder] Implement {target_entity} from ArXiv"
    pr_body  = build_pr_body(alert, branch_name, file_path, generated_at)

    try:
        label_obj = repo.get_label(PR_LABEL_NAME)
        pr = repo.create_pull(
            title=pr_title,
            body=pr_body,
            head=branch_name,
            base=default_branch,
        )
        pr.add_to_labels(label_obj)
        safe_print(f"[OK]    PR opened: #{pr.number} → {pr.html_url}")
        return pr.html_url
    except GithubException as exc:
        safe_print(f"[ERROR] Could not open PR: {exc}")
        raise


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------

def run_auto_coder(alerts: list[dict], mock: bool = False) -> None:
    """Process every Opportunity alert that has a target_entity."""
    candidates = [
        a for a in alerts
        if a.get("type", "").lower() == "opportunity"
        and a.get("target_entity")
    ]

    if not candidates:
        safe_print("[INFO] No actionable Opportunity alerts with a target_entity. Nothing to do.")
        return

    mode_label = "MOCK (template)" if mock else "Gemini AI"
    safe_print(f"\n[RADAR] Auto-Coder starting — {len(candidates)} candidate(s) | mode: {mode_label}\n")
    pr_urls = []

    for i, alert in enumerate(candidates, start=1):
        entity = alert.get("target_entity", "unknown")
        safe_print(f"{'─'*50}")
        safe_print(f"[{i}/{len(candidates)}] Target entity : {entity}")
        safe_print(f"            Paper         : {alert.get('paper_title', '?')}")

        try:
            # Step A — generate code (Gemini or local template)
            if mock:
                safe_print("[MOCK]   Generating template code locally (no API call)...")
                code = generate_mock_code(alert)
                safe_print(f"[MOCK]   Code generated ({len(code)} chars).")
            else:
                code = generate_code_with_gemini(alert)
                safe_print(f"[GEMINI] Code generated ({len(code)} chars).")

            # Step B — commit + PR
            pr_url = create_pull_request(GITHUB_TOKEN, GITHUB_ORG, GITHUB_REPO, alert, code)
            if pr_url:
                pr_urls.append(pr_url)

        except Exception as exc:
            safe_print(f"[ERROR] Failed for '{entity}': {exc}")
            continue

    safe_print(f"\n{'═'*50}")
    safe_print(f"[DONE] {len(pr_urls)} Pull Request(s) created:")
    for url in pr_urls:
        safe_print(f"       → {url}")
    safe_print(f"{'═'*50}\n")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    import argparse
    parser = argparse.ArgumentParser(description="RADAR Auto-Coder: generate code and submit PRs.")
    parser.add_argument(
        "--mock", action="store_true",
        help="Skip Gemini API — generate a rich local template and still create the GitHub PR."
    )
    args = parser.parse_args()

    # Credential guards (Gemini key only required outside mock mode)
    missing = []
    if not GITHUB_TOKEN or GITHUB_TOKEN == "YOUR_GITHUB_PAT_HERE":
        missing.append("GITHUB_TOKEN")
    if not GITHUB_REPO:
        missing.append("GITHUB_REPO")
    if not args.mock and (not GOOGLE_API_KEY or GOOGLE_API_KEY == "YOUR_GOOGLE_API_KEY_HERE"):
        missing.append("GOOGLE_API_KEY  (or run with --mock to skip Gemini)")

    if missing:
        safe_print(
            "[ERROR] The following credentials are not configured:\n"
            + "\n".join(f"        • {m}" for m in missing)
            + "\n\n"
            "        Set them as environment variables, e.g. (PowerShell):\n"
            "            $env:GITHUB_TOKEN   = 'ghp_...'\n"
            "            $env:GITHUB_REPO    = 'Chakrika6/SAMSUNG_PRISM'\n"
            "            $env:GOOGLE_API_KEY = 'AIza...'\n\n"
            "        Or skip Gemini entirely and demo the PR pipeline:\n"
            "            python outputs/auto_pr.py --mock"
        )
        sys.exit(1)

    alerts = load_pending_actions()
    if not alerts:
        safe_print("[INFO] pending_actions.json is empty. Nothing to process.")
        return

    run_auto_coder(alerts, mock=args.mock)


if __name__ == "__main__":
    main()
