"""
Member 4 – The Communicator | outputs/github_dispatcher.py
===========================================================
Reads `contracts/pending_actions.json` produced by Member 3's Brain Engine.
For every item whose `type` is "Opportunity", autonomously creates a heavily
Markdown-formatted GitHub Issue on a target repository using the PyGithub library.

Usage
-----
1. Install dependency:
       pip install PyGithub

2. Set credentials as environment variables (recommended) OR edit the
   constants block below:
       GITHUB_TOKEN      – Personal Access Token with `repo` scope
       GITHUB_REPO       – Full repo name, e.g.  "Chakrika6/SAMSUNG_PRISM"

3. Run from the SAMSUNG_PRISM root directory:
       python outputs/github_dispatcher.py
"""

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

from github import Github, GithubException
from dotenv import load_dotenv

# Ensure project root is in path (needed when run as subprocess)
sys.path.insert(0, str(Path(__file__).parent.parent))
load_dotenv(dotenv_path=Path(__file__).parent.parent / ".env")

# ---------------------------------------------------------------------------
# Configuration – set via environment variables or edit directly here
# ---------------------------------------------------------------------------
GITHUB_TOKEN: str = os.getenv("GITHUB_TOKEN", "YOUR_GITHUB_PAT_HERE")
GITHUB_ORG:   str = os.getenv("GITHUB_ORG")   # New: Target Organization
GITHUB_REPO:  str = os.getenv("GITHUB_REPO")  # Fallback: Specific Repo

# Path to contract (relative to this script)
SCRIPT_DIR            = Path(__file__).parent          # outputs/
CONTRACTS_DIR         = SCRIPT_DIR.parent / "contracts"
PENDING_ACTIONS_PATH  = CONTRACTS_DIR / "pending_actions.json"

# Issue label that will be auto-created on the repo if it doesn't exist
OPPORTUNITY_LABEL     = "RADAR: Opportunity"
OPPORTUNITY_COLOR     = "0e8a16"   # GitHub green


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_pending_actions() -> list[dict]:
    """Load the alert list from contracts/pending_actions.json."""
    if not PENDING_ACTIONS_PATH.exists():
        print(f"[ERROR] Contract file not found: {PENDING_ACTIONS_PATH}")
        sys.exit(1)
    with open(PENDING_ACTIONS_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    # Support both flat list (old) and {"actions": [...]} (new)
    if isinstance(data, dict) and "actions" in data:
        return data["actions"]
    if isinstance(data, list):
        return data
        
    print("[ERROR] pending_actions.json must contain a JSON array or {'actions': []} object.")
    sys.exit(1)


def safe_print(msg: str) -> None:
    """Print with UTF-8 encoding to handle emoji on Windows terminals."""
    sys.stdout.buffer.write((msg + "\n").encode("utf-8", errors="replace"))
    sys.stdout.buffer.flush()


def ensure_label(repo, name: str, color: str, description: str = "") -> None:
    """Create the label on the repo if it doesn't already exist."""
    try:
        repo.get_label(name)
        safe_print(f"[INFO] Label '{name}' already exists.")
    except GithubException:
        try:
            repo.create_label(name=name, color=color, description=description)
            safe_print(f"[INFO] Created label '{name}' on repo.")
        except GithubException as exc:
            safe_print(f"[WARN] Could not create label '{name}': {exc}")


def build_issue_body(alert: dict) -> str:
    """
    Build a rich Markdown body for the GitHub Issue.

    Reads these fields from the alert dict (Member 3's contract):
        paper_title, url, type, reason, action, target_entity (optional)
    """
    paper_title   = alert.get("paper_title",   "Unknown Paper")
    url           = alert.get("url",            "")
    reason        = alert.get("reason",         "No reason provided.")
    action        = alert.get("action",         "No action specified.")
    target_entity = alert.get("target_entity",  "N/A")
    generated_at  = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    paper_link = f"[{paper_title}]({url})" if url else f"**{paper_title}**"

    body = f"""
## 🤖 RADAR — Automated Opportunity Alert

> *Auto-generated by the RADAR Autonomous Agent on {generated_at}*

---

### 📄 Source Paper
| Field | Details |
|---|---|
| **Title** | {paper_link} |
| **ArXiv URL** | {url if url else "N/A"} |
| **Flagged As** | `Opportunity` |

---

### 🧠 Why This Matters
> {reason}

---

### 🎯 Target Entity (from Brain Engine)
This opportunity has been directly linked to the following entity identified by Member 3:

```
{target_entity}
```

---

### ⚡ Recommended Action
- [ ] {action}

---

### 📋 Next Steps
1. **Review** the linked paper for implementation feasibility.
2. **Assign** this issue to the relevant team member.
3. **Close** this issue once the benchmark / experiment is complete.

---
*🔗 Generated by RADAR · Member 4: The Communicator · `outputs/github_dispatcher.py`*
""".strip()

    return body


# ---------------------------------------------------------------------------
# Core dispatcher
# ---------------------------------------------------------------------------

def find_best_repo(g, org_name, target_entity, fallback_repo=None):
    """
    Intelligently find the best repository in the org for a given target_entity.
    """
    if not org_name:
        if fallback_repo:
            return g.get_repo(fallback_repo)
        return None

    try:
        org = g.get_organization(org_name)
        repos = org.get_repos()
        
        # Simple matching: see if target_entity is in the repo name
        target_entity_clean = target_entity.lower().replace(" ", "-")
        
        for repo in repos:
            if target_entity_clean in repo.name.lower():
                return repo
        
        # Fallback to the first repo or specified GITHUB_REPO if no match
        if fallback_repo:
            return g.get_repo(fallback_repo)
            
        return None
    except Exception as e:
        safe_print(f"[ERROR] Could not query organization '{org_name}': {e}")
        return None

def dispatch_opportunities(token: str, org_name: str, fallback_repo: str, alerts: list[dict]) -> None:
    """Intelligently route every Opportunity alert to the correct repo in the Org."""
    g = Github(token)

    opportunities = [a for a in alerts if a.get("type", "").lower() == "opportunity"]

    if not opportunities:
        safe_print("[INFO] No Opportunity alerts found. No Issues will be created.")
        return

    safe_print(f"[INFO] Found {len(opportunities)} Opportunity alert(s). Routing to Organization: {org_name if org_name else 'N/A'}")

    for alert in opportunities:
        target_entity = alert.get("target_entity", "General")
        repo = find_best_repo(g, org_name, target_entity, fallback_repo)

        if not repo:
            safe_print(f"[WARN] Skipping alert: Could not find target repo for entity '{target_entity}'")
            continue

        safe_print(f"[INFO] Routing alert for '{target_entity}' to repo: {repo.full_name}")

        # Ensure labels exist on THIS specific repo
        ensure_label(repo, OPPORTUNITY_LABEL, OPPORTUNITY_COLOR, "Auto-generated by RADAR agent")
        ensure_label(repo, "AI-Generated", "6f42c1", "Issue automatically created by AI")
        ensure_label(repo, "Priority: High", "d73a4a", "High priority optimization")

        title = f"[Priority: High] [AI-Generated] RADAR Opportunity: {alert.get('paper_title', 'Unknown Paper')}"
        body  = build_issue_body(alert)

        try:
            issue = repo.create_issue(
                title=title,
                body=body,
                labels=[repo.get_label(OPPORTUNITY_LABEL), repo.get_label("AI-Generated"), repo.get_label("Priority: High")],
            )
            safe_print(f"[OK] Issue created in {repo.name}: #{issue.number} - {issue.html_url}")
        except GithubException as exc:
            safe_print(f"[WARN] Failed to create issue in '{repo.name}': {exc}")

    safe_print("[DONE] GitHub dispatch complete.")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    if GITHUB_TOKEN == "YOUR_GITHUB_PAT_HERE":
        print(
            "[ERROR] GITHUB_TOKEN is not set.\n"
            "        Generate a Personal Access Token at:\n"
            "            https://github.com/settings/tokens\n"
            "        Then export it:\n"
            "            $env:GITHUB_TOKEN = '<your-token>'  (PowerShell)\n"
            "            export GITHUB_TOKEN=<your-token>    (Linux/Mac)"
        )
        sys.exit(1)

    alerts = load_pending_actions()

    if not alerts:
        print("[INFO] No alerts found in pending_actions.json. Nothing to dispatch.")
        return

    dispatch_opportunities(GITHUB_TOKEN, GITHUB_ORG, GITHUB_REPO, alerts)


if __name__ == "__main__":
    main()
